### ISSUE TITLE
Failing to import full volume

### ISSUE THREAD

**Issue by SlicerMorph** [acetylsalicyl/SlicerRawImageGuess#10]
I am trying to import a 7.5GB vol file from VG Studio. Dimensions are 1199x1644x1950 and it is uint16.

When I enter these to RawImageGuess, it only show the partial contents and  there is this warning:
```
Switch to module:  "RawImageGuess"
Warning: In D:\D\S\Slicer-1-build\VTK\IO\Image\vtkImageReader2.cxx, line 687
vtkImageReader2 (000001941E065EE0): File operation failed.

Generic Warning: In D:\D\S\Slicer-1-build\VTK\IO\Image\vtkImageReader2.cxx, line 757
File operation failed. row = 1196, Read = 2398, FilePos = -1

``` 
I can see the whole volume fine in Fiji using the same settings in their raw image import tool:

![image](https://user-images.githubusercontent.com/45026482/113635805-23e3fe00-9626-11eb-896d-de2feb2a3c3c.png)

**Comment by lassoan** [comment]
How much physical RAM do you have and how much virtual memory have you configured for your system? For managing a 7.5GB volume, I would recommend 75 GB physical RAM, but if that is not feasible then at least allocate that much virtual memory.

If you are sure that the parameters are correct then you can generate the header and use that to load the image. A different image reader used for the preview, which may be more memory efficient.

**Comment by muratmaga** [comment]
Yes, saving the NHDR, and loading the full volume via NHDR worked fine! I am going to close this, as we will actually generate the header via parsing the log file, but it may confuse other people. 

FYI, this is on computer with 32GB RAM and 64GB virtual memory (windows 10).

**Comment by SlicerMorph** [comment]
Yes, saving the NHDR, and loading the full volume via NHDR worked fine! I am going to close this, as we will actually generate the header via parsing the log file, but it may confuse other people.

FYI, this is on computer with 32GB RAM and 64GB virtual memory (windows 10).
