### ISSUE TITLE
Remove hard limits for dimensions and spacing in the UI

### ISSUE THREAD

**Issue by ludwigseibt** [acetylsalicyl/SlicerRawImageGuess#13]
Hey, thank you for your Extension!

I am trying to import a raw dataset, but the dimensions are X=3000, Y=3000 and  the spacing is .00025. These values cannot be entered into the interface.

Could the max and min values for these variables be extended?

**Comment by lassoan** [comment]
You can adjust the maximum ranges in the advanced section at the bottom.

**Comment by ludwigseibt** [comment]
Thank you. My mistake.
