### ISSUE TITLE
Only partial import along z axis.

### ISSUE THREAD

**Issue by johandinox** [acetylsalicyl/SlicerRawImageGuess#8]
Thanks a lot for writing this code. I encountered a problem that I could not solve:
When I load a dataset, some slices towards the ends (along z) are missing.
In ImageJ and in Amira I can see the full dataset. Re-encoding from 32 bit floats in little-endian order to 16 bit integers in big-endian order did not help with the clipping. When converting to 8bit, the full stack was sucessfully loaded, which may point toward a memory problem?
Changing in this line the min to a max also didn't help.
https://github.com/acetylsalicyl/SlicerRawImageGuess/blob/6358603dfe0b67f16cad7346161b936a340395cc/RawImageGuess/RawImageGuess.py#L271
Do you have any ideas what the reason for partial loading in z could be?

**Comment by lassoan** [comment]
Can you share a sample data set that shows this problem?

What format you are converting from? If you create a .nhdr filed header (simple text file describing type and dimensions of your data set) when you export the raw file then you can load the data directly into Slicer (without RawImageGuess).

**Comment by johandinox** [comment]
Thanks for the prompt response. I can see the whole dataset now, here is how:
Following your advice with the .nhdr header, I generated the header via the RawImageGuess module, closed the dataset (that was only loaded partially) and then opened the .nhdr file with 3dslicer and the whole data was loaded. So it seems like RawImageGuess creates the right header but the RawImageGuess' "Update" button does not do the same like addData> load .nhdr file.
I can currently only share the .raw dataset  (16GB) non-publicly if needed, shall I?

**Comment by lassoan** [comment]
Maybe you have run out of memory while loading the image. If it happens to others, too, then we can reopen this for more investigation.
